server:
  port: 8001

msa:
  cart-service:
    url: localhost:8000
  user-service:
    url: localhost:8002


spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
      max-lifetime: 30000
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true